Result processor integration
macformula/hil pull request #54
Opened 2024-01-17 01:25 UTC by samparent97

2024-01-21 19:04 UTC, itshady requested changes
If you cd into cmd/clidispatchertest and try to build and run, it will immediately error when simpledispatcher runs a test

2024-01-22 16:41 UTC, samparent97 commented
@itshady this is likely related to the configurations in your `config.yaml`. The current configurations are specific to my setup.

2024-01-23 18:20 UTC, TylerStAmour approved these changes

2024-01-23 18:22 UTC, itshady commented
@samparent97 approved it, good catch

2024-01-23 18:30 UTC, merged